#! /bin/bash
if [ "$#" -gt 1 ]; then
	echo "Illegal number of parameters"
	echo "USAGE: gitrepo [github_repo_name]"
	echo "Default github_repo_name will be the current working directory name if not provided"
	exit 1
fi

# auto populated from install.sh here with python and file path
# >>>>>>
python3 /home/spicy/fun/repos/gitrepo/gitrepo.py $1
