#! /bin/bash
if [ "$#" -gt 1 ]; then
	echo "Illegal number of parameters"
	echo "USAGE: gitrepo [github_repo_name]"
	echo "Default github_repo_name will be the current working directory name if not provided"
	exit 1
fi

# replace with your python and gitrepo.py locations 
<insert python path here> <insert git_repo.py path here> $1
